name: Back End Deployment
on:
  push:
    branches:
      - main

env:
  BUILD_NUMBER: ${{ github.run_number }}
  IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/api-cinema
  PROJECT_PATH: /home/user/devops-script-cinema/backend/dev
  DOCKER_SERVICE: backend-api 

jobs:
  # Analyse Qualité Code
  sonarqube-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.analysis.autoDisabled=true

  # Scan Sécurité Docker
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy --version
      
      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }} .
      
      - name: Scan Docker Image
        run: trivy image ${{ env.IMAGE_NAME }}

  # Scan Vulnérabilités Dépendances
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Snyk
        run: npm install -g snyk
      
      - name: Snyk Auth
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      
      - name: Snyk Scan
        run: snyk test --all-projects

  # Build et Push
  Build_And_Push:
    runs-on: ubuntu-latest
    needs: [sonarqube-scan, trivy-scan, snyk-scan]
    steps:
      - name: checkout code
        uses: actions/checkout@v5
    
      - name: Build Docker Image
        run: docker build -t ${{env.IMAGE_NAME}} .

      - name: Tag Docker Image with version
        run: |
          docker tag ${{env.IMAGE_NAME}} ${{env.IMAGE_NAME}}:v${{env.BUILD_NUMBER}}
          docker tag ${{env.IMAGE_NAME}} ${{env.IMAGE_NAME}}:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker images
        run: |
          docker push ${{env.IMAGE_NAME}}:v${{env.BUILD_NUMBER}}
          docker push ${{env.IMAGE_NAME}}:latest

  Deployment:
    runs-on: ubuntu-latest
    needs: Build_And_Push
    steps:
      - name: ssh connect and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ${{ env.PROJECT_PATH }}
            sudo docker compose -p cinema pull backend-api
            sudo docker compose -p cinema up -d backend-api